### ISSUE TITLE
Not withdrawing

### ISSUE THREAD

**Issue by coulterj** [brndnmtthws/optimal-buy-gdax#16]
I have not been watching when it stopped working, but it looks like the script is no longer moving my coins to my external wallets.  Funds in BTC are over .05 Could this be part of the move to Coinbase Pro?

Anyway looking at the logs, and I don't see any obvious errors.

**Comment by brndnmtthws** [comment]
In your case it looks like since you have more than $5, it's not withdrawing. It won't withdraw until the balance drops below $5, although you can configure that.

On a somewhat related note, I noticed some weirdness with the Coinbase API this morning as well. In my case I had a fiat balance, and the Coinbase API returned an 'insufficient funds' error. I re-ran it and everything worked the second time around, so that sounds like a bug with Coinbase to me (perhaps they have some sort of eventually consistent data model underneath).

**Comment by coulterj** [comment]
Thanks for the help!  You were right.  It was the withdraw balance.  I originally changed that because that also controls how much BTC it will purchase.  At the default of $25, it won't place bids if the balance drops below $25.  I would like for it to use all of the cash if possible.  Is there a setting I can have it attempt to transfer the BTC every time and spend all of my money?

**Comment by brndnmtthws** [comment]
Yeah, it's possible with code changes, but the current behaviour optimizes for doing one big transaction rather than many smaller transactions. I can add it to the pipeline as a feature request, or you can put together a patch :)

The logic is here: https://github.com/brndnmtthws/optimal-buy-gdax/blob/master/optimal_buy_gdax/optimal_buy_gdax.py#L309-L318

You could change the logic to withdraw when the balance is greater than the minimum withdraw amount, for example. Or you could even remove the check altogether and just always withdraw. Given that Coinbase eats the fee for withdrawals, I guess it doesn't matter, but if they start charging a fee then I might want to revert the behaviour to batch.

**Comment by coulterj** [comment]
Ok. not much of a coder, but maybe able to take that on.  I will try to look at it this weekend.  Thanks for the help, I do appreciate the script.
